author:
    name: Aniket Thakkar
    twitter: thakkarjr
    email: aniket.thakkar@gmail.com

site:
    title: Aniquez
    production_url: http://aniquez.com

TEMPLATE_CONTEXT_PROCESSORS:
    - django.core.context_processors.request
    - django.contrib.auth.context_processors.auth
    - _theme.views.context_processor

DISCUSS_SHORTNAME: aniquez

